play_everywhere:
  description: Play on all Bose Soundtouch devices.
  fields:
    master:
      description: Name of the master entity that will coordinate the grouping. Platform dependent. It is a shortcut for creating a multi-room zone with all devices
      example: "media_player.soundtouch_home"

create_zone:
  description: Create a Sountouch multi-room zone.
  fields:
    master:
      description: Name of the master entity that will coordinate the multi-room zone. Platform dependent.
      example: "media_player.soundtouch_home"
    slaves:
      description: Name of slaves entities to add to the new zone.
      example: "media_player.soundtouch_bedroom"

add_zone_slave:
  description: Add a slave to a Sountouch multi-room zone.
  fields:
    master:
      description: Name of the master entity that is coordinating the multi-room zone. Platform dependent.
      example: "media_player.soundtouch_home"
    slaves:
      description: Name of slaves entities to add to the existing zone.
      example: "media_player.soundtouch_bedroom"

remove_zone_slave:
  description: Remove a slave from the Sounttouch multi-room zone.
  fields:
    master:
      description: Name of the master entity that is coordinating the multi-room zone. Platform dependent.
      example: "media_player.soundtouch_home"
    slaves:
      description: Name of slaves entities to remove from the existing zone.
      example: "media_player.soundtouch_bedroom"

snapshot:
  description: Take a snapshot of the media player.
  fields:
    entity_id:
      description: Name(s) of entities that will be snapshot.
      example: "media_player.soundtouch_home"

restore:
  description: Restore a snapshot of the media player.
  fields:
    entity_id:
      description: Name(s) of entities that will be restored.
      example: "media_player.soundtouch_home"
    restore_volume:
      description: True (default) or False. Indicates if the volume also needs to be restored.
      example: "false"

handoff:
  description: Handoff playing source from 1 SoundTouch to another.
  fields:
    from:
      description: Name of the entity that is currently playing
      example: "media_player.soundtouch_home"
    to:
      description: Name of entity that needs to play what the 'from' entity was playing.
      example: "media_player.soundtouch_bedroom"
    restore_volume:
      description: True or False (default). Indicates if the volume also needs to be handoffed.
      example: "true"
    snapshot_only:
      description: True or False (default). Indicates if only the snapshot needs to be handoffed, but does't trigger the restore and power off.
      example: "true"